### ISSUE TITLE
add alias for SublimeText2 from Terminal

### ISSUE THREAD

**Issue by jyw2116** [railsbridge-boston/railsbridge-boston#17]
Hey again everyone!

So, the other thing I wanted to mention was, since we're recommending Sublime Text 2 as our text editor of choice for the workshop-

as part of the Friday installation, maybe we could include a guide for adding the alias for SublimeText2 from Terminal?

I've had several people ask me about this, and I think this might save a lot of time in getting through the Saturday curriculum.

Thanks!

**Comment by danchoi** [comment]
Is someone willing to make the necessary edit to the curriculum and make a pull request? @slothbear?

**Comment by slothbear** [comment]
I agree. A couple of students figured this out on their own and suggested to me that we add the instructions. I'll do it.

**Comment by danchoi** [comment]
Thank you

**Comment by slothbear** [comment]
Now that I'm tried implementing this addition (#24), I'm dropping my support of the idea. It feels like there are too many concepts (sudo, symlink), and too many ways for the instructions to fail. I couldn't figure out the best way for Windows (see 9 different answers here: http://stackoverflow.com/questions/9440639/sublime-text-from-command-line-win7).

Once students are using Sublime Text, it would be better to inform students of the "Open" or "Open Folder" menu commands (as recently documented by Janet) to open the full Rails project. Since all files edited during the course are in the Rails project hierarchy, the 'subl' symlink becomes superfluous.

If we keep these instructions, they really belong in the Extra Credit bin -- not part of the main instructions.

**Comment by brendankemp** [comment]
Agreed @slothbear, closing.
