### ISSUE TITLE
Update for Rails 4

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#66]
Rails 4 will be coming down the pipe VERY soon and that will change a large portion of a content, primarily the index.html section. We should determine how we should replace this content.

**Comment by danchoi** [comment]
Right on about Rails 4.  

Related to this, @alexch from the RailsBridge SF mothership would really like to find a way for all the RailsBridges springing up all over the world to be able to collaborate on a common curriculum content codebase. See #4.

We might make the curriculum content a modular component consisting of just a set of markdown files and metadata that can be shared by all the RailsBridge workshops, but which would still allow for each RailsBridge to add their own UI layer and navigation on top of the content. Maybe the curriculum content could be pulled in as a git submodule into our website repo.

OR we can make a curriculum API server that serves up curriculum content as JSON resources. I like this idea too. This can increase modularity and reuse and collaboration.

**Comment by drapergeek** [comment]
I think the idea of storing content in a different way but I'm actually not in favor of merging the content. I think the ability to modify content and use it differently in different areas is a huge benefit. I like the fact that if we want to try something new (i.e. removing Git from the curriculum) we can do that.

**Comment by danchoi** [comment]
I agree with you about the benefits of decentralization and local experimentation. 

What if we had a separate repo for the RailsBridge Boston curriculum, which would contain the lesson Markdown files and also the web UI and the little curriculum progress tracker and other things.

This could be a Sinatra app that could be pulled in as a git submodule and mounted as a Rack endpoint in the config.ru of the main RBB website, or it could be served out of a different Heroku app altogether.

The curriculum repo would be controlled by RailsBridge Boston, but it would also be more reusable by other RailsBridges if they want to use or fork our version of the curriculum.

**Comment by drapergeek** [comment]
I think that sounds awesome.

Overall I've been considering a proposal to moving the app to a full blown rails app. There are a few more features I would like to add to make it a bit more CMS style and I think that a certain point it makes sense to use rails.

Features I would like to add (open for feedback):
- Storing TAs in the db.
- Storing lecturers and their lectures in the db.
- Storing sponsors in the db.

**Comment by danchoi** [comment]
I think converting to Rails with a DB is a good idea. It will let us reuse
information more easily and also keep a better history of which sponsors
and which TAs participated in which workshops.

We can turn the workshop webapp into a Rails app, and maybe spin off a
separate GitHub repo for the curriculum.

**Comment by danchoi** [comment]
Just a note; here is the SF RailsBridge workshop resources website

http://curriculum.railsbridge.org/docs/

**Comment by alexch** [comment]
Please look at the infrastructure we have set up for railsbridge before converting stuff. It would be so awesome if we merged.

This Sinatra+Erector system is working pretty well for us, and I personally think Rails is overkill/inappropriate for a mostly-static document-heavy site.

**Comment by mxie** [comment]
@alexch I think we're talking about 2 separate things here: 1) a change in the curriculum (whether it's content-wise or storage-wise) and 2) the workshop web app.

RE: 1) I'm not entirely convinced that we should _merge_ curriculum content between chapters. I do, however, think it's a great idea to compare content and see how we could each improve what we currently have. From there, we could create or revise a list of suggested topics (a "base" curriculum, let's say) and then leave it to each chapter to figure out how they'd like to present it and/or add other material as appropriate.

RE: 2) Since we're not using any sort of "central" website, I think it's ok for each RB chapter to use whatever works best for them to organize themselves, and in this case, it might be to convert our current site to Rails.

More generally, I think I agree with the changes @drapergeek and @danchoi have proposed/discussed.

**Comment by slothbear** [comment]
@mxie you missed the 3rd thing we're talking about – _Update for Rails 4_ :smirk_cat: 

I like that we can do different things, but the cost of a separate curriculum is high. The SF curriculum is used many times a year, maintained and contributed to by lots of folks. The Boston curriculum is used 4 times a year, maintained by a small handful of folks. Just this weekend students brought these issues, all of which are already handled in the SF curriculum:
- Multiple styles used to indicate `stuff to type`
- `stuff to type` style was also used by other headers, not to be typed
- Sometimes no clear delineation between _Stuff to do_, and _Explanation of what we did_.
- "Is it ok that my Rails version is 3.2.13 but the instructions say 3.2.1?"

If we have a better way of doing something, I'd like to see the better way implemented in the core curriculum to benefit all Railsbridge students.

If we have a difference of opinion on particular sections, I like what I think Dan is suggesting – making those sections modular enough to turn on and off as needed.

**Comment by mxie** [comment]
Well, the Rails 4 thing is really part of the 1st thing I mentioned - changing the curriculum.

Also, I think we're agreeing on the same thing here, @slothbear...having the same core curriculum and then somehow being able to some parts "on or off" - though depending on what those parts are, it might be extremely hard, e.g. Git. Some think that removing Git from the curriculum would drive better focus on learning Rails, but it also means changing the whole curriculum to not involve the Git processes at all. This is probably something that not all chapters agree on.

In any case though, can we at least agree that we need to do some cross-reviewing of content between chapters (or at least between SF and Boston?) _first_ before we start doing any sort of adding/subtracting/changing of stuff?

**Comment by slothbear** [comment]
I think Dan already has this working in his head, but having optional content shouldn't be too hard. Mark the git-related files and steps with a `:git_feature` flag, then start up the system with a list of the optional features you want.

Oh wait. I see what you mean. Now we're talking about changing the core curriculum software to support optional content – just so we can remove it. Maybe it could still work if the benefits were great enough. How many chapters maintain their own curriculum, and why? Would they be served by this optional file/step method, or perhaps another approach?

**Comment by danchoi** [comment]
I like the structured curriculum build system RailsBridge SF uses (see e.g. [raw source file for CRUD with scaffolding](https://github.com/railsbridge/docs/blob/master/sites/curriculum/CRUD_with_scaffolding.step)). When we started last fall, though, we wanted to port the curriculum to a Bootstrap look and feel, and also embed it in our own website instead of serve up the content in standalone fashion. 

So RailsBridge Boston (thanks to @brendankemp) scraped the HTML output of these source files and back-converted them to straight Markdown, without the structuring DSL. (Yes, weird but it worked.) This is how we maintain the RBB curriculum source files now.  

We gained some things by doing this. But we lost a level of abstraction and versatility by flattening the content to just straight Markdown. So I think the original sourcefiles encoded with the Step DSL do have some virtues that we lost. I think re-adding some domain-specific markup to the curriculum files is a good idea that will open new possibilities for what we can do with the curriculum.

But we could be more cutting edge and write a real custom parser and a real Rails web curriculum source document language. The source document language could be designed by the whole team, and the parser would transform these source documents downstream into HTML or even JSON (and served to the webpage through some JavaScript MVC framework like AngularJS).  

The advantage over the Ruby DSL would be less noise, eliminating the <<-HEREDOC delimiters. the block ({}) delimiters, the underscores in the DSL keywords, and other artifacts of having to write source docs in legal Ruby syntax. **The new source document language could look like a superset of Markdown.**

As for the parser/translator for the new markup language, Haskell is a great language for this. I'd be happy to take a crack if people want to try this path.

**Comment by drapergeek** [comment]
I think personally I would prefer to see us use the exact same DSL that SF is using. Ideally if we use the same DSL, we can use their curriculum where we want to and is easy to swap out when we don't want to. Though I like the idea a custom markdown language I think making it easy to just use what they have would be easier overall and parse that into our own site.

**Comment by danchoi** [comment]
OK I'm perfectly fine with that.

**Comment by drapergeek** [comment]
Should we still separate the 'site' and the curriculum into two repos or keep it all together? I like the idea of only having one place to point people who want to help but breaking it out may be easier for those looking to only work with the curriculum.

**Comment by danchoi** [comment]
What about using a [Git submodule](http://git-scm.com/book/en/Git-Tools-Submodules) to stick our fork of railsbridge/docs into our project tree? Then we can have the best of both worlds. We can keep everything in one app, and be able to contribute back to railsbridge/docs through our own fork of it. 

We would need to write some code to allow us to generate railsbridge/doc curriculum HTML from the RBB Rails app (or from a Sinatra app mounted in it) and embed the markup into our website layout and navigation.

**Comment by drapergeek** [comment]
Sounds like a plan. I think @mxie and I are going to start on this today actually.

**Comment by danchoi** [comment]
Wait, there is another alternative to discuss: We can turn the railsbridge/docs project into a gem that you can drop into the Rails Gemfile and then embed into the site in various ways. The gem approach would be simpler for Rubyists to grok than Git submodules, especially when it comes to versioning. But in this case we should convince @alexch to let us gemify the railsbridge/docs project structure and to adopt those changes upstream.

**Comment by drapergeek** [comment]
I'm not sure exactly how this works, but it is possible that it is because of the lack of coffee intake so far.

At this moment my primary goal is to do the simplest thing possible to be able to start consuming the steps that SF has and then we can decide what the best split is.

**Comment by danchoi** [comment]
Let me (and whoever else is interested) try to discuss this with @alexch
as soon as we can to resolve this jointly. I think the gem approach is
better in the long run & better for all the RailsBridges. I'll
create an issue about this at railsbridge/docs to get @alexch's attention.

On Fri, Jun 28, 2013 at 09:19 AM, Jason Draper notifications@github.com wrote:

> from: Jason Draper notifications@github.com
> date: Fri, Jun 28 06:19 AM -07:00 2013
> to: railsbridge-boston/railsbridge-boston railsbridge-boston@noreply.github.com
> cc: Daniel Choi dhchoi@gmail.com
> reply-to: railsbridge-boston/railsbridge-boston reply@reply.github.com
> subject: Re: [railsbridge-boston] Update for Rails 4 (#66)
> 
> I'm not sure exactly how this works, but it is possible that it is because of the lack of coffee intake so far.
> 
> At this moment my primary goal is to do the simplest thing possible to be able to start consuming the steps that SF has and then we can decide what the best split is.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/railsbridge-boston/railsbridge-boston/issues/66#issuecomment-20187369

---

Sent from Vmail
http://danielchoi.com/software/vmail.html

**Comment by danchoi** [comment]
https://github.com/railsbridge/docs/issues/208

**Comment by danchoi** [comment]
@drapergeek @mxie @jsteiner and @danchoi discussed this in person today in the thoughtbot conference room. We are all agreed on 1st starting to update the railsbridge/docs curriculum to target Rails 4, and then later to gemify our fork of railsbridge/docs so it can be incoporated into our upcoming Rails 4 workshop website.
