### ISSUE TITLE
Git Commit Issues

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#7]
I had a few participants accidentally get stuck in vim due to just using `git commit` without the message option.  This can be a bit off-putting  (especially if your TA is not a vim user and has to ask someeone else for assistance).  Would it be worth it to have the students specify their editor as sublime since thats what we're recommending as an editor?

**Comment by brendankemp** [comment]
+1 worth it.

**Comment by houhoulis** [comment]
+1 Being a newcomer and unexpectedly having your terminal pop into vim can be very unsettling.  I have started switching people's default editor to TextEdit/Notepad anytime I've helped someone through an "installfest".  I'd recommend we give instructions for a few editors since not everyone can use SublimeText.  Will submit pull request.
