### ISSUE TITLE
Extra Credit Idea

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#9]
A somewhat simplified walkthrough off adding another field to a model I think would be received quite well.  As soon as we generated the first scaffold the next question from multiple participants was "cool, now how do I add X".  I think a walkthrough of adding maybe the email field to user or something like that would be interesting and would involve multiple steps (generating a migration, adding it to the form, adding it to the show, index and attr_accessible).

**Comment by brendankemp** [comment]
What if we used this as the "checkpoint" at the end of the associations section, instead of building an association between User and Vote? I've heard that the current check is confusing, because 1) associations are hard 2) there are currently no changes to the view, so students deploy to Heroku and can't tell if it worked.

**Comment by drapergeek** [comment]
Actually I would prefer to keep them both.  The people I was working with didn't seem to dislike the associations, they actually enjoyed it, would just be nice to somehow get it on the view for heroku.  I haven't thought out how to do that exactly.

**Comment by kgf** [comment]
What if we added something to the end of application.html.erb near the bottom, like a version number. This would be a worthwhile lesson, short and easy to accomplish, and it would show on Heroku.
